import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Footer from "@/components/ui/footer";
import { ChauffeurSidebar } from "@/components/chauffeur/chauffeurSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100vh] h-full`}
        >
          <SidebarProvider>
            <ChauffeurSidebar/>
              <div className="flex flex-col min-h-[100vh] justify-between h-full w-full">
                {children}
                <Footer/>
              </div>
          </SidebarProvider>
      </body>
    </html>
  );
}
